### ISSUE TITLE
selection highlight not working

### ISSUE THREAD

**Issue by lsilvam** [fools-mate/night-owl-obsidian-theme#1]
Hi, 

thanks for taking time to make this theme.
I tried it, but for example when scrolling files from `ctrl+o` menu its not possible to see which files is being highlighted.

**Comment by meseck** [comment]
Thanks for pointing that out, I had really overlooked it. 👍 

Fixed with newest commit/build: a1927c800d1d49159acd8cbcea2b3b80b4caa342
